name: unit-tests
on:
    push:
        branches:
            - '**'

    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Setup
              run: npm ci

            - name: Test
              run: |
                  npm run test:ci
